### ISSUE TITLE
Alright y'all...what do we still have to do?

### ISSUE THREAD

**Issue by SadPearStudios** [McSwags/average-problem-child-game#12]
Some of the things that come to mind (lemme know if I miss something):
- LEVEL DESIGN
- ENEMY AI (I GOT THIS)
- CHARACTER DESIGN
- SECRET AREAS
- DOORS

Also btw what are y'alls Discords, i finally managed to convince my parents to let me install it ;)

**Comment by McSwags** [comment]
@munquavion

**Comment by McSwags** [comment]
@uncooked_kod

**Comment by jacob-spencer** [comment]
resolved
